name: Reusable
on:
  workflow_call:
    inputs:
      required_input:
        required: true
        type: string
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.required_input }}"
